superfablab/superfablab/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from . import views

from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar


urlpatterns = [
    path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("station/", include("visit_tracking.urls")),
    path('', views.index, name='home'),
    path('me/profile', views.profile, name='profile'),
    path('staff/user_list', views.users_in_space, name = 'user_list'),
    path('training/', include("tools_and_trainings.urls")),
    path('stats', views.stats, name='stats'),
    path('users-per-day-chart/', views.users_per_day_chart, name="chart"),
    path('__debug__/', include(debug_toolbar.urls)),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superfablab/tools_and_trainings/urls.py
from django.urls import path
from . import views

app_name = 'station'

urlpatterns = [
    path('create/', views.create_training, name="create_training"),
]

superfablab/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:user_id>/update_canvas_id", views.update_users_canvas_ID),
]

superfablab/tools_and_trainings/models.py
from __future__ import annotations

from django.db import models
from django.conf import settings
from typing import List
from users.models import SpaceUser

class TrainingCategory(models.Model):
    name = models.TextField()
    canvas_id = models.IntegerField(null=True, blank=True)
    user_url = models.TextField(null=True, blank=True)
    
    @property
    def name_readable(self):
        return self.name.replace("_", " ")
    
    def __str__(self):
        return self.name

class TrainingManager(models.Manager):
    def get_users_trainings(self, user: SpaceUser) -> List[Training]:
        trainings = list(self.filter(user=user).order_by("category", "-training_level").distinct("category").all())
        return trainings
class Training(models.Model):
    class TrainingLevels(models.IntegerChoices):
        APPRENTICE = 0
        OPERATOR = 30
        TRAINER = 70
        CERTIFIER = 100
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="trainings")
    category = models.ForeignKey(TrainingCategory, on_delete=models.PROTECT, related_name="trainings")
    training_level = models.IntegerField(choices=TrainingLevels.choices, default=TrainingLevels.APPRENTICE)
    certifier = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name="given_trainings")
    completed_on = models.DateTimeField(auto_now_add=True)
    objects = TrainingManager()
    
    @property
    def hex_color(self):
        match self.training_level:
            case Training.TrainingLevels.APPRENTICE:
                return "#C33D2A"
            case Training.TrainingLevels.OPERATOR:
                return "#3E9955"
            case Training.TrainingLevels.TRAINER:
                return "#1F70B8"
            case Training.TrainingLevels.CERTIFIER:
                return "#D1A300"
            case _:
                return "#FFFFFF"
    
    @property
    def icon(self):
        match self.training_level:
            case Training.TrainingLevels.APPRENTICE:
                return "fa-shoe-prints"
            case Training.TrainingLevels.OPERATOR:
                return "fa-dumbbell"
            case Training.TrainingLevels.TRAINER:
                return "fa-medal"
            case Training.TrainingLevels.CERTIFIER:
                return "fa-chess-king"
            case _:
                return ""
    
    def __str__(self):
        return f"{self.get_training_level_display()} in {self.category}"

superfablab/tools_and_trainings/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from .models import Training, TrainingCategory
from django.utils.timezone import now, localtime
from visit_tracking.models import Visit
from users.models import SpaceUser
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.contrib.auth import get_user_model



def staff_required(view_func):
    return user_passes_test(lambda u: u.space_level >= get_user_model().SpaceLevel.KEYHOLDER)(view_func)

def certify_ability(view_func):
    return user_passes_test(lambda u: Training.objects.filter(user=u, training_level__gte=Training.TrainingLevels.TRAINER).exists() )(view_func)


@certify_ability
def create_training(request):
    if request.POST:
        print(f"POST {request.POST}")
        user = SpaceUser.objects.get(niner_id=request.POST['user'])
        category = TrainingCategory.objects.get(id=request.POST['category'])
        certifier = request.user
        training = Training.objects.create(user=user, category=category, training_level=request.POST['level'], certifier=certifier)

        return redirect("home")  
    for training in TrainingCategory.objects.all():
        try:
            to = Training.objects.get(category=training, user=request.user, training_level__gte=Training.TrainingLevels.TRAINER)
            available_trainings[training] = []
            for training_level in Training.TrainingLevels.choices:
                if training_level[0] < to.training_level:
                    available_trainings[training].append(training_level)
                    continue
                    
                if to.training_level == Training.TrainingLevels.CERTIFIER:
                    available_trainings[training].append(training_level)
        except Training.DoesNotExist as e:
            try:
                print(Training.objects.get(category=training, user=request.user))
            except Training.DoesNotExist as e:
                print(f"user: {request.user} does not have any training {training}")
        
    
    context = {
        "current_visits": list(Visit.objects.get_signed_in_users()),
        "available_trainings": available_trainings,
    }
    
    return render(request, "training_form.html", context)
   
#version of create_training that is only used in the code. cannot be called from post.
# used to have system assign training to users automatically after they complete a training quiz.    
def create_training_internal(user, category, level, certifier):    
    Training.objects.create(user=user, category=category, training_level=level, certifier=certifier)

superfablab/tools_and_trainings/templates/training_form.html
{% extends "base.html" %}



{% block title %}SFL - Create Training{% endblock %}

{% block content %}

<div id="loading-indicator" class="modal">
    <style>
      .loader-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      
      .loader {
        border: 6px solid rgba(0, 0, 0, 0.1);
        border-top-color: #00d1b2; /* Bulma primary color */
        border-radius: 50%;
        width: 80px; /* Adjust size */
        height: 80px; /* Adjust size */
        animation: spin 1s linear infinite;
      }
      
      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
      </style>    
    <div class="modal-background"></div>
    <div class="modal-content has-text-centered">
      <div class="loader-wrapper">
        <div class="loader"></div>
        <p class="has-text-white mt-4">Fetching User Data...</p>
      </div>
    </div>
  </div>


<section class="section">
    <div class="container">
      <div class="columns is-vcentered is-centered">
        <div class="column is-half">
          <div class="box">
            <h2 class="title is-4 has-text-centered">Add Training to a User</h2>
            <form method="post">
              {% csrf_token %}
  
              <div class="field">
                <label for="id_user" class="label">User</label>
                <div class="control select">
                  <select name="user">
                    <option disabled selected value> -- select a User -- </option>
                    {% for visit in current_visits %}
                        <option value={{ visit.niner_id }}>{{ visit }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>  
  
  
              <div class="field">
                <label for="id_category" class="label">Training Category</label>
                <div class="control select">
                    <select name="category", id="category">
                    <option disabled selected value> -- select a training -- </option>
                    {% for training_category, available_trainings in available_trainings.items %}
                          <option value={{ training_category.id }}>{{ training_category.name_readable }}</option>
                    {% endfor %}
                    </select>
                  </div>
              </div>
  
  
              <div class="field">
                  <label for="id_level" class="label">Training Level</label>
                  <div class="control select">
                    <select name="level" id="level">
                        <option disabled selected value> -- select the level -- </option>
                        {% for training_category, available_trainings in available_trainings.items %}
                            {% for level in available_trainings %}
                            <option parent={{ training_category.id }} value={{ level.0 }}>{{ level.1 }}</option>
                            {% endfor %}
                        {% endfor %}
                    </select>
                  </div>
                </div>
  
              
  
              <div class="field">
                <div class="control">
                  <button type="submit" class="button is-primary is-fullwidth">Add Training</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <script>
    var document = window.document;
    $(document).ready(function(){

        var $field1var=$("#category");
        var $field2var=$("#level");

        var $field2options=$field2var.find('option');

        $field2var.html($field2options.filter('[value=""]'));

        $field1var.on('change',function(){
            $field2var.html($field2options.filter('[parent="'+this.value+'"],[value=""]'));
            $('#field2 option[value=""]').prop('selected', true);

        });
    });
</script> 


{% endblock %}